### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by consultmoh** [1970Mr/news-portal#3]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mr1970/laravel-modules, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by 1970Mr** [comment]
Hi @consultmoh,

Thank you so much for bringing this to my attention. It looks like I accidentally renamed the module. I've fixed the issue now, and everything should be working correctly.

I really appreciate your help! If you encounter any more issues, please feel free to let me know.

**Comment by consultmoh** [comment]
Also I noticed it's in Persian language, how can I make it Defualt English
and make the menu bar to be on the left rather than the right. Thank you
